name: Build nextlib

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build nextlib
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Validate Gradle Wrapper
      #   uses: gradle/wrapper-validation-action@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: sdkmanager "cmake;3.31.6"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Project with gradle
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4.5.0
        with:
          name: nextlib-release
          path: |
            ./media3ext/build/outputs/aar/media3ext-release.aar
            ./mediainfo/build/outputs/aar/mediainfo-release.aar

